#!/usr/bin/env node
const spawn = require('child_process').spawn;
const assert = require('assert')
import{partitionBy, flatten} from 'curtiz-utils';

// https://gist.github.com/masayu-a/e3eee0637c07d4019ec9 "prepared by Irena Srdanovic, 17.1.2013, checked by Ogiso, Den
// and Maekawa"
const partOfSpeechKeys = [
  "代名詞",
  "pronoun",
  "副詞",
  "adverb",
  "助動詞",
  "auxiliary_verb",
  "助詞",
  "particle",
  "係助詞",
  "binding",
  "副助詞",
  "adverbial",
  "接続助詞",
  "conjunctive",
  "格助詞",
  "case",
  "準体助詞",
  "nominal",
  "終助詞",
  "phrase_final",
  "動詞",
  "verb",
  "一般",
  "general",
  "非自立可能",
  "bound",
  "名詞",
  "noun",
  "助動詞語幹",
  "auxiliary",
  "固有名詞",
  "proper",
  "人名",
  "name",
  "名",
  "firstname",
  "姓",
  "surname",
  "地名",
  "place",
  "国",
  "country",
  "数詞",
  "numeral",
 